### ISSUE TITLE
nice try.

### ISSUE THREAD

**Issue by akrhzof** [inon-13/free-mega-hack#2]
LMAO NICE TRY 
WE ARENT DUMB 
THAT THERES A RAT

**Comment by akrhzof** [comment]
btw the "installer" for mega hack 7

**Comment by inon-13** [comment]
all i did was actually buy the mega hack and copy the files thats it idc if you dont believe me and i dont know how to put a rat in a software or in anything. if you want dont believe me idc. the installer and the mega hack v7 does not work but they are actually the files. they will not give you any "free" mega hack but it will be the same software as the installer itself and again if you dont believe me dont install it and i might actually delete the files cuz he has copyright.
